# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SZTableViewManagerExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  platform :ios, '7.0'
  pod 'SZTableViewManager', :path => '../'
  # Pods for SZTableViewManagerExample

  target 'SZTableViewManagerExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SZTableViewManagerExampleUITests' do
    # Pods for testing
  end

end
